# Generated by Django 4.2.9 on 2024-08-30 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0001_initial"),
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteFishingPond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "fishing_pond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="fish.fishingpond",
                        verbose_name="鱼塘",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_fishing_ponds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户收藏鱼塘",
                "verbose_name_plural": "用户收藏鱼塘",
                "db_table": "favorite_fishing_pond",
                "unique_together": {("user", "fishing_pond")},
            },
        ),
    ]
