# Generated by Django 5.1 on 2024-08-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0002_favoritefishingpond"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phoneNumber",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
