# Generated by Django 5.1 on 2024-09-01 07:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0003_alter_customuser_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="userId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="唯一标识符"
            ),
        ),
    ]
