# Generated by Django 5.1 on 2024-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0005_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritefishingpond",
            name="userId",
            field=models.CharField(
                default=1, max_length=255, unique=True, verbose_name="用户id"
            ),
            preserve_default=False,
        ),
    ]
