# Generated by Django 5.1 on 2024-09-16 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_management", "0006_favoritefishingpond_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoritefishingpond",
            name="userId",
        ),
        migrations.AlterField(
            model_name="favoritefishingpond",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_ponds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
