# Generated by Django 4.2.9 on 2024-08-30 05:55

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FishingPond",
            fields=[
                (
                    "pond_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="鱼塘ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="鱼塘名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="鱼塘简介")),
                (
                    "rating",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="鱼塘评分",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="鱼塘价格",
                    ),
                ),
                (
                    "pond_type",
                    models.CharField(
                        choices=[
                            ("wild", "野塘"),
                            ("black_pit", "黑坑"),
                            ("natural", "天然"),
                            ("happy", "欢乐"),
                        ],
                        max_length=20,
                        verbose_name="鱼塘类型",
                    ),
                ),
                ("image_base64", models.TextField(verbose_name="鱼塘图片 (Base64编码)")),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, verbose_name="鱼塘电话"),
                ),
                (
                    "opening_time",
                    models.TimeField(blank=True, null=True, verbose_name="营业开始时间"),
                ),
                (
                    "closing_time",
                    models.TimeField(blank=True, null=True, verbose_name="营业结束时间"),
                ),
                (
                    "fish_species",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        null=True,
                        size=None,
                        verbose_name="鱼种类",
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="鱼塘位置"
                    ),
                ),
            ],
            options={
                "verbose_name": "鱼塘",
                "verbose_name_plural": "鱼塘",
                "db_table": "fishing_pond",
                "indexes": [
                    models.Index(
                        fields=["location"], name="fishing_pon_locatio_438e30_idx"
                    )
                ],
            },
        ),
    ]
