# Generated by Django 5.1 on 2024-08-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishingpond",
            name="image_base64",
            field=models.TextField(
                blank=True, null=True, verbose_name="鱼塘图片 (Base64编码)"
            ),
        ),
        migrations.AlterField(
            model_name="fishingpond",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="鱼塘电话"
            ),
        ),
    ]
