# Generated by Django 5.1 on 2024-09-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0003_fishingpond_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishingpond",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="是否公开"),
        ),
    ]
