# Generated by Django 5.1 on 2024-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0004_fishingpond_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishingpond",
            name="user_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户"
            ),
        ),
    ]
