# Generated by Django 5.1 on 2024-09-16 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0005_fishingpond_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fishingpond",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="fishingpond",
            name="user_id",
        ),
    ]
