# Generated by Django 5.1 on 2024-09-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fish", "0006_remove_fishingpond_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fishingpond",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="是否公开"),
        ),
        migrations.AddField(
            model_name="fishingpond",
            name="user_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="用户"
            ),
        ),
    ]
